### ISSUE TITLE
Illegal instrucktion

### ISSUE THREAD

**Issue by Neisven** [cions/termux-deno#2]
![Screenshot_20240216-192133_Termux](https://github.com/cions/termux-deno/assets/156550353/54dd1b5f-713a-4b46-981a-af6bcefae8f8)
![Screenshot_20240216-191947_Termux](https://github.com/cions/termux-deno/assets/156550353/9a2711ca-36d9-4af9-bad4-3ede12e0a139)

After installing the deno from the link I received the following error

**Comment by cions** [comment]
The linked binary is optimized for my phone, Cortex-A75.
Your CPU is Cortex-A53, which doesn't support some features that the A75 supports. Please build yourself.
